export const GET_TAG_LIST_SUCCESS = 'GET_TAG_LIST_SUCCESS'
export const GET_TAG_LIST_FAILURE = 'GET_TAG_LIST_FAILURE'
export const GET_POST_LIST_SUCCESS = 'GET_POST_LIST_SUCCESS'
export const GET_POST_LIST_FAILURE = 'GET_POST_LIST_FAILURE'
